version: "3.8"

services:
  cypress:
    container_name: cypress-bdd
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: cypress-bdd-framework:latest
    environment:
      ENV: ${ENV:-dev}
    volumes:
      - ./reports/screenshots:/app/reports/screenshots
      - ./reports/videos:/app/reports/videos
      - ./reports/allure-results:/app/reports/allure-results
      - ./reports/mochawesome:/app/reports/mochawesome
      - ./reports/cucumber-report:/app/reports/cucumber-report
      - ./reports/logs:/app/reports/logs
    working_dir: /app
    ipc: host
    init: true
    security_opt:
      - seccomp:unconfined
